buildH = read.table("../OUT.buildH.popc0-25ns_dt1000.xtc.out")
JMelcr = read.table("OUT.progJMeclr.popc0-25ns_dt1000_H.out")

pdf("comp_JMelcrProg.pdf")
barplot(buildH$V5 - JMelcr$V5, names=buildH$V1, las=2, ylim=c(-0.1, 0.1), cex.names=0.5)
abline(h=0.02, lty=2)
abline(h=-0.02, lty=2)
grid()
MEAN = mean(buildH$V5 - JMelcr$V5)
TITLE = paste("Mean diff buildH - JMelcrProg =", MEAN)
title(TITLE)
print(TITLE)
print("Results plotted in comp_JMelcrProg.pdf")
dev.off()