name: buildh
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # BuildH dependencies
  - pip
  - pip:
    - -r file:../requirements.txt
  # Jupyter lab and visualisation
  - matplotlib
  - jupyterlab
  # Tests
  - pytest
  # Lint
  - pylint
  - pycodestyle
  - pydocstyle
  # Packaging
  - python-build
  - twine
  - bump2version
  # Documentation
  - sphinx
  - nbsphinx
  - myst-parser
  - pip:
    - sphinx-book-theme