name: buildh
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - jupyterlab
  - pytest
  - pylint
  - pycodestyle
  - pydocstyle
  - bump2version
  - pip:
    - -r file:../requirements.txt
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - pip:
    - nbsphinx-link
    - recommonmark
    - sphinx-git
 