name: GitHub CI doc

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
  
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - name: Install Miniconda and env
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: buildh
        environment-file: binder/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
    - shell: bash -l {0}
       run: |
          conda info
          printenv | sort
    - name: Build documentation
      shell: bash -l {0}
      run: |
        conda activate buildh
        make docs